// frontend/CretasFoodTrace/src/components/attachment/AttachmentList.tsx
/**
 * AttachmentList — 列出某实体的全部附件 (缩略图 + 文件名 + 上传时间).
 *
 * 用法:
 *   <AttachmentList entityType="PURCHASE_ORDER" entityId={order.id} refreshKey={x} />
 *
 * @author Cretas Team — Track C
 * @since 2026-05-15 (C-ATT-1 Day 4)
 */

import React, { useEffect, useState } from 'react';
import { View, StyleSheet, Image, FlatList, TouchableOpacity, Linking } from 'react-native';
import { Text, ActivityIndicator, Card, IconButton } from 'react-native-paper';
import { attachmentApi, Attachment, AttachmentEntityType } from '../../services/api/attachmentApi';

interface Props {
  entityType: AttachmentEntityType;
  entityId: string;
  factoryId?: string;
  /** 当父组件需触发刷新, 改这个值. */
  refreshKey?: number;
  onDelete?: (att: Attachment) => void;
  emptyText?: string;
}

export function AttachmentList({ entityType, entityId, factoryId, refreshKey, onDelete, emptyText }: Props) {
  const [list, setList] = useState<Attachment[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    attachmentApi
      .list(entityType, entityId, factoryId)
      .then((data) => {
        if (!cancelled) setList(data);
      })
      .catch((e) => {
        if (!cancelled) setError(e?.message ?? '加载附件失败');
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [entityType, entityId, factoryId, refreshKey]);

  const open = (a: Attachment) => {
    Linking.openURL(a.fileUrl).catch(() => {
      setError(`无法打开: ${a.fileName}`);
    });
  };

  const handleDelete = async (a: Attachment) => {
    try {
      await attachmentApi.delete(a.id, factoryId);
      setList((prev) => prev.filter((x) => x.id !== a.id));
      onDelete?.(a);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : '删除失败';
      setError(msg);
    }
  };

  if (loading) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="small" />
      </View>
    );
  }

  if (error) {
    return <Text style={styles.error}>{error}</Text>;
  }

  if (list.length === 0) {
    return <Text style={styles.empty}>{emptyText ?? '暂无附件'}</Text>;
  }

  return (
    <FlatList
      data={list}
      keyExtractor={(item) => item.id}
      scrollEnabled={false}
      renderItem={({ item }) => (
        <Card style={styles.card}>
          <View style={styles.row}>
            <TouchableOpacity onPress={() => open(item)} style={styles.thumbBox}>
              {item.thumbnailUrl || item.fileCategory === 'PHOTO' ? (
                <Image
                  source={{ uri: item.thumbnailUrl ?? item.fileUrl }}
                  style={styles.thumb}
                  resizeMode="cover"
                />
              ) : (
                <View style={[styles.thumb, styles.fileIcon]}>
                  <Text style={styles.fileIconText}>{getCategoryIcon(item.fileCategory)}</Text>
                </View>
              )}
            </TouchableOpacity>
            <View style={styles.meta}>
              <Text numberOfLines={1} style={styles.fileName}>
                {item.fileName}
              </Text>
              <Text style={styles.subText}>
                {formatSize(item.fileSize)} · {formatTime(item.uploadedAt)}
              </Text>
              {item.description ? (
                <Text numberOfLines={2} style={styles.subText}>
                  {item.description}
                </Text>
              ) : null}
            </View>
            <IconButton icon="delete-outline" onPress={() => handleDelete(item)} accessibilityLabel="删除附件" />
          </View>
        </Card>
      )}
    />
  );
}

function getCategoryIcon(c: Attachment['fileCategory']): string {
  switch (c) {
    case 'VIDEO':
      return '🎬';
    case 'DOCUMENT':
      return '📄';
    case 'VOUCHER':
      return '🧾';
    case 'SIGNATURE':
      return '✍️';
    default:
      return '📎';
  }
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

function formatTime(iso: string): string {
  try {
    const d = new Date(iso);
    return `${d.getMonth() + 1}/${d.getDate()} ${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
  } catch {
    return iso;
  }
}

const styles = StyleSheet.create({
  card: { marginVertical: 4, padding: 8 },
  row: { flexDirection: 'row', alignItems: 'center' },
  thumbBox: { marginRight: 12 },
  thumb: { width: 56, height: 56, borderRadius: 6, backgroundColor: '#e8e8e8' },
  fileIcon: { justifyContent: 'center', alignItems: 'center' },
  fileIconText: { fontSize: 24 },
  meta: { flex: 1 },
  fileName: { fontWeight: '600', fontSize: 14 },
  subText: { fontSize: 12, color: '#666', marginTop: 2 },
  center: { padding: 16, alignItems: 'center' },
  empty: { padding: 16, color: '#999', textAlign: 'center' },
  error: { padding: 16, color: '#d32f2f', textAlign: 'center' },
});

// web-admin/src/components/attachment/AttachmentList.vue
<template>
  <div class="attachment-list">
    <el-skeleton v-if="loading" :rows="2" animated />
    <el-alert v-else-if="error" :title="error" type="error" :closable="false" />
    <el-empty v-else-if="list.length === 0" :description="emptyText ?? '暂无附件'" :image-size="60" />
    <div v-else class="att-grid">
      <el-card
        v-for="att in list"
        :key="att.id"
        class="att-card"
        shadow="hover"
        body-style="padding: 8px"
      >
        <div class="att-row">
          <div class="att-thumb" @click="open(att)">
            <el-image
              v-if="att.fileCategory === 'PHOTO'"
              :src="att.thumbnailUrl ?? att.fileUrl"
              fit="cover"
              :preview-src-list="[att.fileUrl]"
              :initial-index="0"
              class="thumb-img"
            />
            <div v-else class="thumb-icon">{{ categoryIcon(att.fileCategory) }}</div>
          </div>
          <div class="att-meta">
            <div class="att-name" :title="att.fileName">{{ att.fileName }}</div>
            <div class="att-sub">
              {{ formatSize(att.fileSize) }} · {{ formatTime(att.uploadedAt) }}
            </div>
            <div v-if="att.description" class="att-desc">{{ att.description }}</div>
          </div>
          <el-button text :icon="Delete" @click="handleDelete(att)" aria-label="删除附件" />
        </div>
      </el-card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Delete } from '@element-plus/icons-vue';
import {
  listAttachments,
  deleteAttachment,
  type Attachment,
  type AttachmentEntityType,
  type AttachmentFileCategory,
} from '@/api/attachment';

interface Props {
  entityType: AttachmentEntityType;
  entityId: string;
  factoryId?: string;
  /** 改变此 key 触发重拉. */
  refreshKey?: number;
  emptyText?: string;
}

const props = defineProps<Props>();
const emit = defineEmits<{ deleted: [att: Attachment] }>();

const list = ref<Attachment[]>([]);
const loading = ref(false);
const error = ref<string | null>(null);

async function load(): Promise<void> {
  if (!props.entityId) return;
  loading.value = true;
  error.value = null;
  try {
    const r = await listAttachments(props.entityType, props.entityId, props.factoryId);
    list.value = r.data ?? [];
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : '加载附件失败';
  } finally {
    loading.value = false;
  }
}

watch(
  () => [props.entityType, props.entityId, props.refreshKey],
  () => load(),
  { immediate: true },
);

function open(att: Attachment): void {
  if (att.fileCategory === 'PHOTO') return; // el-image preview 已处理
  window.open(att.fileUrl, '_blank');
}

async function handleDelete(att: Attachment): Promise<void> {
  try {
    await ElMessageBox.confirm(`确定删除附件 "${att.fileName}" ?`, '确认', {
      confirmButtonText: '删除',
      cancelButtonText: '取消',
      type: 'warning',
    });
    await deleteAttachment(att.id, props.factoryId);
    list.value = list.value.filter((x) => x.id !== att.id);
    emit('deleted', att);
    ElMessage.success('已删除');
  } catch (e: unknown) {
    if (e === 'cancel') return;
    const msg = e instanceof Error ? e.message : '删除失败';
    ElMessage.error(msg);
  }
}

function categoryIcon(c: AttachmentFileCategory): string {
  switch (c) {
    case 'VIDEO':
      return '🎬';
    case 'DOCUMENT':
      return '📄';
    case 'VOUCHER':
      return '🧾';
    case 'SIGNATURE':
      return '✍️';
    default:
      return '📎';
  }
}

function formatSize(b: number): string {
  if (b < 1024) return `${b} B`;
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} KB`;
  return `${(b / 1024 / 1024).toFixed(1)} MB`;
}

function formatTime(iso: string): string {
  try {
    const d = new Date(iso);
    return `${d.getMonth() + 1}/${d.getDate()} ${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
  } catch {
    return iso;
  }
}

defineExpose({ reload: load });
</script>

<style scoped>
.attachment-list {
  width: 100%;
}
.att-grid {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.att-card {
  width: 100%;
}
.att-row {
  display: flex;
  align-items: center;
  gap: 12px;
}
.att-thumb {
  cursor: pointer;
  width: 56px;
  height: 56px;
  border-radius: 6px;
  overflow: hidden;
  background: #f4f4f5;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
}
.thumb-img {
  width: 56px;
  height: 56px;
  border-radius: 6px;
}
.thumb-icon {
  font-size: 26px;
}
.att-meta {
  flex: 1;
  min-width: 0;
}
.att-name {
  font-weight: 600;
  font-size: 14px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.att-sub,
.att-desc {
  font-size: 12px;
  color: #909399;
  margin-top: 2px;
}
.att-desc {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
</style>
